### ISSUE TITLE
Exciting project!

### ISSUE THREAD

**Issue by richardliaw** [microsoft/archai#1]
Hey all, I'm from the Ray team. Really excited to see this repository!

I saw that there were some things that needed to be monkey patched on Ray Tune. Is there anything we should do to make that integration easier? 

Happy to jump on a call to chat more.

**Comment by sytelus** [comment]
Hi @richardliaw, thank you so much for connecting and your support. The monkey patching was done to intercept best accuracy among all trials at every step when `TrialRunner.step()` gets called in Ray Tune. This is done just for logging best matrix at every step. Ia there a better way to do this? Any other hooks we can use?

Thanks!

**Comment by richardliaw** [comment]
Hm, I've run into this issue too and I've used the "trial_executor" to do this:

```
from ray.tune.ray_trial_executor import RayTrialExecutor

class HookExecutor(RayTrialExecutor):
    def on_step_begin(self, runner):
       trials = runner.get_trials()
       print(max(t.last_result.get("acc") for t in trials))
```

**Comment by krfricke** [comment]
Hi @sytelus, we're currently in the process of implementing a callback API for Ray Tune. We would like to make sure that our implementation would be actually usable for you. It would be great if we could get some quick feedback from you.

Here's a link to the PR where we introduce the callback API: https://github.com/ray-project/ray/pull/11001. There's a short usage example included.

For your use case, I'd think that implementing the `Callback.on_step_begin` method would work. Could you take a quick look and confirm if this is the case? If not, it would be great to hear what we could improve in the API before we merge it into Ray Tune.

Thanks!

**Comment by sytelus** [comment]
Hi @richardliaw - one of the issue we are facing is due to pickle5 check in `ray.init()`. I'd filed issue here: https://github.com/ray-project/ray/issues/10637 and on our side related issue is https://github.com/microsoft/archai/issues/10. It will be great if you can do something about it!

**Comment by richardliaw** [comment]
@sytelus thanks a bunch for the ping! Can you try ray 1.0 or the nightly installation of Ray?

https://docs.ray.io/en/master/installation.html#latest-snapshots-nightlies
`pip install -U [link to wheel]`

Please let me know if you run into any issues.
