### ISSUE TITLE
Dependencies not installed properly by running install.sh

### ISSUE THREAD

**Issue by johnyquest7** [microsoft/archai#10]
Dependencies not installed properly by running install.sh

Following was the output after running install.sh

```
+ conda install -y -c conda-forge pickle5
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining _sysroot_linux-64_curr_repodata_hack:   5%| | 3/56 [00:00<00:00, 29194Examining pyparsing:   7%|█▍                  | 4/56 [00:00<00:00, 31068.92it/s]Examining certifi:  11%|██▎                   | 6/56 [00:00<00:00, 33599.23it/s]
Comparing spe-  that have this dependency:   0%|          | 0/2 [00:00<?, ?it/s]
Finding shortest conflict path for certifi[version='>=2016.9.26']:   0%| | 0/3 [Finding shortest co\ lict path for certifi[version='>=2016.09']:  33%|▎| 1/3 [00Finding shortest conflict path for certifi[version='>=2016.09']:  67%|▋| 2/3 [00Finding shortest conflict path for ca-certificates:  67%|▋| 2/3 [00:00<00:00, 15Finding shortest conflict path for ca-certificates: 100%|█| 3/3 [00:00<00:00,- 1Comparing specs that have this dependency:  50%|█ | 1/2 [00:00<00:00,  3.38it/s]Finding shortest conf\ ct path for certifi[version='>=2016.9.26']:  25%|▎| 1/4 [Finding shortest conflict path for certifi[version='>=2016.9.26']:  50%|▌| 2/4 [Finding shortest co| lict path for certifi[version='>=2016.09']:  50%|▌| 2/4 [00Finding shortest conflict path for certifi[version='>=2016.09']:  75%|▊| 3/4 [00Findin- shortest conflict path for ca-certificates:  75%|▊| 3/4 [00:03<00:00,  1Examining python:  55%|█████████████▊           | 31/56 [00:04<00:08,  2.92it/s]Comparing specs that have this dependency:   0%|          | 0/2 [00:00<?, ?it/s]Finding shortest confli\  path for python=3.8:  10%| | 1/10 [00:00<00:00, 18558.Finding shortest conflict path for python_abi=3.8[build=*_cp38]:  20%|▏| 2/10 [0Finding shortest conflict path for python:  30%|▎| 3/10 [00:00<00:00, 23.39it/s]Finding shortest conflict path for python[version='>=3.8,<3.9.0a0']:  40%|▍| 4/1Finding shortest conflict path for python=3.8:  50%|▌| 5/10 [00:00<00:00, 31.18iFinding shortest conflict path for python[version='>=3.6,<3.7.0a0']:  60%|▌| 6/1Finding shortest conflict path for python[version='>=3']:  70%|▋| 7/10 [00:00<00Finding shortest conflict path for python=3.6:  80%|▊| 8/10 [00:00<00:00, 31.18iFinding shortest conflict path for python[version='>=3.7,<3.8.0a0']:  90%|▉| 9/1Comparing spe|  that have this dependency:  50%|█ | 1/2 [00:00<00:00,  7.61it/s]Finding shortest conflict path for python_abi=3.6[build=*_cp36m]:   0%| | 0/10 [Finding shortest conflict path for python=3.7:  10%| | 1/10 [00:00<00:02,  3.42iFinding shortest conflict path for python=3.7:  20%|▏| 2/10 [00:00<00:01,  6.83iFinding shortest conf/ ct path for python_abi=3.7[build=*_cp37m]:  20%|▏| 2/10 [Finding shortest conflict path for python:  30%|▎| 3/10 [00:00<00:01,  6.83it/s]Finding shortest conflict path for python=3.8:  40%|▍| 4/10 [00:00<00:00,  6.83iFinding shortest conflict path for python=3.8:  50%|▌| 5/10 [00:00<00:00,  8.80iFinding shortest conflict pa-  for python[version='>=3.6,<3.7.0a0']:  50%|▌| 5/1Finding shortest conflict path for python_abi==3.6[build=*_pypy36_pp73]:  60%|▌|Finding short\ t conflict path for python[version='>=3']:  70%|▋| 7/10 [00:00<00Finding shortest conflict path for python[version='>=3']:  80%|▊| 8/10 [00:00<00Finding shortest conflict path for python=3.6:  80%|▊| 8/10 [00:00<00:00, 10.49ifailed                                                                                                                                                          UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pickle5 -> python[version='3.6.*|3.7.*']
  - pickle5 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:



Package setuptools conflicts for:
pickle5 -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools
python=3.8 -> pip -> setuptools
Package certifi conflicts for:
python=3.8 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
pickle5 -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
Package ca-certificates conflicts for:
python=3.8 -> openssl[version='>=1.1.1g,<1.1.2a'] -> ca-certificates
pickle5 -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.0.2o,<1.0.3a'] -> ca-certificates
Package python_abi conflicts for:
python=3.8 -> pip -> setuptools -> python_abi=3.8[build=*_cp38]
```

After running install.sh 
tried running main.py

got following error

    import yaml
ModuleNotFoundError: No module named 'yaml'

So I installed yaml using 
Conda installed yaml

Once I fixed it - another error popped up

    from overrides import EnforceOverrides
ModuleNotFoundError: No module named 'overrides'

**Comment by debadeepta** [comment]
Can you let us know Linux version and anaconda version please?

**Comment by johnyquest7** [comment]
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

conda 4.7.12

created conda environment with python 3.8 
also tried with 3.6

then installed pytorch with 
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch

followed by

gitclone archai repo and running install.sh

**Comment by johnyquest7** [comment]
After installing few packages manually, I was able to make it work.
But this is the output I got from running - python scripts/main.py --algos darts
only last few lines posted
Does this look right?

`21:47 eval_arch gpu_names=GeForce RTX 2070, gpu_count=1, CUDA_VISIBLE_DEVICES=NotSet, cudnn.enabled=True, cudnn.benchmark=True, cudnn.deterministic=False, cudnn.version=7605
21:47 eval_arch memory=svmem(total=33482334208, available=28672196608, percent=14.4, used=4209995776, free=26437681152, active=4939554816, inactive=1376739328, buffers=154157056, cached=2680500224, shared=126328832, slab=367112192)
21:47 eval_arch CPUs=8
21:47 eval_arch amp_available=False, distributed_available=False
21:47 eval_arch dist_initialized=False, world_size=1, gpu=0, gpu_ids=[], local_rank=0, global_rank=0
21:47 eval_arch/eval_train steps_per_epoch=1, conf_sched={'type': 'cosine', 'min_lr': 0.001, 'warmup': {'multiplier': 1, 'epochs': 0}}
21:47 eval_arch/eval_train conf_optim={'type': 'sgd', 'lr': 0.025, 'decay': 0.0003, 'momentum': 0.9, 'nesterov': False, 'decay_bn': nan}
21:47 eval_arch/eval_train multi_optim_len=1
21:47 eval_arch/eval_train resumed=False, checkpoint_avail=False, checkpoint_val=False, start_epoch=0, total_epochs=1
21:47 eval_arch/eval_train aux_weight=0.4, grad_clip=5, drop_path_prob=0.2, validation_freq=1, batch_chunks=1
21:47 eval_arch/eval_train/epochs/0/steps/0 top1=0.0625, top5=0.3438, loss=3.319, step_time=0.2066
21:47 eval_arch/eval_train/epochs/0/eval_test/steps/0 top1=0.125, top5=0.5312, loss=2.301, step_time=0.006657
21:47 eval_arch/eval_train/epochs/0/eval_test/steps/1 top1=0.1094, top5=0.5, loss=2.302, step_time=0.004517
21:47 eval_arch/eval_train/epochs/0/eval_test/train top1=0.1094, top5=0.5, loss=2.302, duration=0.09015, step_time=0.005587, end_lr=nan
21:47 eval_arch/eval_train/epochs/0/eval_test/timings epoch=0.09015, step=0.005587, run=0.09049
21:47 eval_arch/eval_train/epochs/0/eval_test/best_train epoch=0, top1=0.1094
21:47 eval_arch/eval_train/epochs/0/train top1=0.0625, top5=0.3438, loss=3.319, duration=0.4997, step_time=0.2066, end_lr=0.001
21:47 eval_arch/eval_train/epochs/0/val top1=0.1094, top5=0.5, loss=2.302, duration=0.09015
21:47 eval_arch/eval_train/timings epoch=0.4997, step=0.2066, run=0.5003
21:47 eval_arch/eval_train/best_train epoch=0, top1=0.0625
21:47 eval_arch/eval_train/best_val epoch=0, top1=0.1094
21:47 eval_arch model_save_path=/home/quest/logdir/darts_cifar10_throwaway_eval/model.pt
Process exit: 6792
`

**Comment by dikshantsagar** [comment]
running `pip install -e .` installs all project dependencies

**Comment by sytelus** [comment]
Thanks for letting us know of this issue. The problem was due to line in install.sh that installs pickle5. The pickle5 install is required for Python 3.7 and below but only if some dependency is using older pickle5 because in those versions built-in pickle doesn't have newer APIs that is used by ray package. The pickle5 is agreeably quite a mess and unfortunately there is no clean solution here. I've asked ray folks to remove pickle5 dependency.

For now, I've fixed this issue by removing pickle5 install. If you get an error in `ray.init()` then you can just run:

```
conda install -y -c conda-forge pickle5
```
