### ISSUE TITLE
[BUG] visualizing graphs in evaluators.ipynb

### ISSUE THREAD

**Issue by lovettchris** [microsoft/archai#163]
**Describe the bug**

arch.view() is cool, this must be a pytorch feature? Unfortunately, for this to work on windows one needs to manually install the graphviz installer from https://www.graphviz.org/download/#windows, I wonder if there's a better solution that integrates more nicely into jupyter?  

What if we did this instead?
```python
m = ss.random_sample()
import torch.onnx
x = torch.zeros(1,3,64,64)  # don't know if there's an easier way to jin up a valid input for the model.
torch.onnx.export(m.arch, x, 'model.onnx', do_constant_folding=True)

# m.arch.view()
!pip install netron
import netron
netron.start('model.onnx', 8081)
```

Everyone has netron installed, and this works nicely on windows and the result is very pretty:

![image](https://user-images.githubusercontent.com/18707114/217408475-a50c5155-340f-4f07-a5a2-c15ea44acb4d.png)

You can also add this to make the diagram show up inline:

```python
import IPython
IPython.display.IFrame(f"http://localhost:8081", width=1000, height=1000)
```

![image](https://user-images.githubusercontent.com/18707114/217410133-143cf3d7-c5bb-4f7d-9be2-77e30edee1f6.png)

**Comment by gugarosa** [comment]
I loved this idea! Didn't even think that it was possible to use `netron` within Python.

What do you think @piero2c ?
