### ISSUE TITLE
[NEW] Use a single plot library across Archai

### ISSUE THREAD

**Issue by gugarosa** [microsoft/archai#176]
**Is your feature request related to a problem? Please describe.**
Right now, we have imports for `matplotlib`, `plotly` and `seaborn`, which at the end of the day, do the same thing.

**Describe the solution you'd like**
Use a single plot library for the package.

**Describe alternatives you've considered**
Either `matplotlib` or preferentially `plotly`.

**Comment by piero2c** [comment]
Good idea. I also prefer `plotly`. One caveat though is that it seems it does not work with sphinx (see the last plot from https://microsoft.github.io/archai/getting_started/notebooks/discrete_search/algos.html). Maybe there's a way to fix that?

**Comment by gugarosa** [comment]
I have a branch `single-plot-lib` that currently removes plotly and seaborn, and uses matplotlib.

I will test it, and then after, change everything to plotly, just to make sure everything is running.
