### ISSUE TITLE
Integration with pytorch lightning?

### ISSUE THREAD

**Issue by christofer-f** [microsoft/archai#4]
Integration with pytorch lightning?
Hi, I like your approach with this repo. I have a question... Do you have any thoughts about joining forces with the pytorch lightning project?

Kind regards,
Christofer

**Comment by sytelus** [comment]
This is great idea. One of our objective is to collect all bag of tricks that people use in training. It would be good idea to work on this jointly!

**Comment by dalide** [comment]
it would be great to integrate with pytorch-lightning
